-- MySQL Script generated by MySQL Workbench
-- Wed 16 Dec 2015 00:47:19 GMT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema prescrib_ex
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `prescrib_ex` ;

-- -----------------------------------------------------
-- Schema prescrib_ex
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `prescrib_ex` DEFAULT CHARACTER SET utf8 ;
USE `prescrib_ex` ;

-- -----------------------------------------------------
-- Table `prescrib_ex`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prescrib_ex`.`user` ;

CREATE TABLE IF NOT EXISTS `prescrib_ex`.`user` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `role` VARCHAR(3) NOT NULL,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `addressline1` VARCHAR(45) NULL,
  `addressline2` VARCHAR(45) NULL,
  PRIMARY KEY (`userID`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `userID_UNIQUE` (`userID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prescrib_ex`.`pharmacist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prescrib_ex`.`pharmacist` ;

CREATE TABLE IF NOT EXISTS `prescrib_ex`.`pharmacist` (
  `regNo` INT NOT NULL,
  `pharmacy` VARCHAR(45) NULL,
  `userID` INT NOT NULL,
  PRIMARY KEY (`regNo`),
  INDEX `userID_idx` (`userID` ASC),
  CONSTRAINT `pharmacist_userID`
    FOREIGN KEY (`userID`)
    REFERENCES `prescrib_ex`.`user` (`userID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prescrib_ex`.`doctor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prescrib_ex`.`doctor` ;

CREATE TABLE IF NOT EXISTS `prescrib_ex`.`doctor` (
  `regNo` INT NOT NULL,
  `userID` INT NOT NULL,
  `practicename` VARCHAR(45) NULL,
  PRIMARY KEY (`regNo`),
  UNIQUE INDEX `idPatient_UNIQUE` (`regNo` ASC),
  INDEX `userID_idx` (`userID` ASC),
  CONSTRAINT `doctor_userID`
    FOREIGN KEY (`userID`)
    REFERENCES `prescrib_ex`.`user` (`userID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prescrib_ex`.`patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prescrib_ex`.`patient` ;

CREATE TABLE IF NOT EXISTS `prescrib_ex`.`patient` (
  `dob` DATE NOT NULL,
  `userID` INT NOT NULL,
  INDEX `userID_idx` (`userID` ASC),
  CONSTRAINT `fk_patient_userID`
    FOREIGN KEY (`userID`)
    REFERENCES `prescrib_ex`.`user` (`userID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prescrib_ex`.`activeingredient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prescrib_ex`.`activeingredient` ;

CREATE TABLE IF NOT EXISTS `prescrib_ex`.`activeingredient` (
  `activeingredientID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NULL,
  PRIMARY KEY (`activeingredientID`),
  UNIQUE INDEX `activeingredientID_UNIQUE` (`activeingredientID` ASC),
  UNIQUE INDEX `uniqueName` USING BTREE (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prescrib_ex`.`frequencyunits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prescrib_ex`.`frequencyunits` ;

CREATE TABLE IF NOT EXISTS `prescrib_ex`.`frequencyunits` (
  `frequencyunitID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`frequencyunitID`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `frequencyunitID_UNIQUE` (`frequencyunitID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prescrib_ex`.`dosageform`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prescrib_ex`.`dosageform` ;

CREATE TABLE IF NOT EXISTS `prescrib_ex`.`dosageform` (
  `dosageformid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`dosageformid`),
  UNIQUE INDEX `dosageformid_UNIQUE` (`dosageformid` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prescrib_ex`.`units`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prescrib_ex`.`units` ;

CREATE TABLE IF NOT EXISTS `prescrib_ex`.`units` (
  `unitID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  PRIMARY KEY (`unitID`),
  UNIQUE INDEX `unitID_UNIQUE` (`unitID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prescrib_ex`.`prescription`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prescrib_ex`.`prescription` ;

CREATE TABLE IF NOT EXISTS `prescrib_ex`.`prescription` (
  `prescriptionID` INT NOT NULL AUTO_INCREMENT,
  `activeingredient` INT NOT NULL,
  `dosage` DOUBLE NULL,
  `dosageunitID` INT NULL,
  `dosageformID` INT NULL,
  `frequency` DOUBLE NULL,
  `frequencyunitID` INT NULL,
  `prescriber` INT NOT NULL,
  `prescriptionExpiry` DATE NULL,
  `instructions` VARCHAR(100) NULL,
  `repeats` INT NULL,
  `repeatsleft` INT NULL,
  `active` TINYINT(1) NULL DEFAULT 1,
  `patientID` INT NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`prescriptionID`),
  INDEX `fk_prescription_1_idx` (`prescriber` ASC),
  INDEX `activeIngredientID_idx` (`activeingredient` ASC),
  INDEX `frequencyunit_idx` (`frequencyunitID` ASC),
  UNIQUE INDEX `prescriptionID_UNIQUE` (`prescriptionID` ASC),
  INDEX `fk_prescription_1_idx2` (`dosageformID` ASC),
  INDEX `fk_patientID_idx` (`patientID` ASC),
  CONSTRAINT `fk_prescription_userID`
    FOREIGN KEY (`prescriber`)
    REFERENCES `prescrib_ex`.`doctor` (`userID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_prescription_activeIngredientID`
    FOREIGN KEY (`activeingredient`)
    REFERENCES `prescrib_ex`.`activeingredient` (`activeingredientID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prescription_frequencyunit`
    FOREIGN KEY (`frequencyunitID`)
    REFERENCES `prescrib_ex`.`frequencyunits` (`frequencyunitID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_prescription_1`
    FOREIGN KEY (`dosageformID`)
    REFERENCES `prescrib_ex`.`dosageform` (`dosageformid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_patientID`
    FOREIGN KEY (`patientID`)
    REFERENCES `prescrib_ex`.`patient` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prescription_2`
    FOREIGN KEY (`dosageunitID`)
    REFERENCES `prescrib_ex`.`units` (`unitID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prescrib_ex`.`genericDrug`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prescrib_ex`.`genericDrug` ;

CREATE TABLE IF NOT EXISTS `prescrib_ex`.`genericDrug` (
  `genericdrugID` INT NOT NULL AUTO_INCREMENT,
  `activeingredientID` INT NOT NULL,
  `licenceNo` VARCHAR(45) NOT NULL,
  `genericName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`genericdrugID`),
  INDEX `fk_genericDrug_1_idx` (`activeingredientID` ASC),
  UNIQUE INDEX `genericdrugID_UNIQUE` (`genericdrugID` ASC),
  UNIQUE INDEX `genericName_UNIQUE` (`genericName` ASC),
  CONSTRAINT `genericdrug_activeingredientID`
    FOREIGN KEY (`activeingredientID`)
    REFERENCES `prescrib_ex`.`activeingredient` (`activeingredientID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prescrib_ex`.`dispensal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prescrib_ex`.`dispensal` ;

CREATE TABLE IF NOT EXISTS `prescrib_ex`.`dispensal` (
  `dispensalID` INT NOT NULL AUTO_INCREMENT,
  `prescriptionID` INT NOT NULL,
  `pharmacistID` INT NOT NULL,
  `genericID` INT NOT NULL,
  `strength` DOUBLE NULL,
  `strengthunitID` INT NULL,
  `pharmacistinstructions` VARCHAR(100) NULL,
  `date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `dispensal_dispensalID` INT NOT NULL,
  PRIMARY KEY (`dispensalID`),
  INDEX `regNo_idx` (`pharmacistID` ASC),
  INDEX `presctiptionID_idx` (`prescriptionID` ASC),
  INDEX `genericdrugID_idx` (`genericID` ASC),
  UNIQUE INDEX `dispensalID_UNIQUE` (`dispensalID` ASC),
  CONSTRAINT `fk_dispensal_regNo`
    FOREIGN KEY (`pharmacistID`)
    REFERENCES `prescrib_ex`.`pharmacist` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dispensal_presctiptionID`
    FOREIGN KEY (`prescriptionID`)
    REFERENCES `prescrib_ex`.`prescription` (`prescriptionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dispensal_genericdrugID`
    FOREIGN KEY (`genericID`)
    REFERENCES `prescrib_ex`.`genericDrug` (`genericdrugID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dispensal_units`
    FOREIGN KEY (`strengthunitID`)
    REFERENCES `prescrib_ex`.`units` (`unitID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
